### ISSUE TITLE
should the section what blockchains is come earlier?

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-702#5]
Maybe we need to look at an outline of the paper via a table of contents to determine that

**Comment by lokeshdubey** [comment]
I haven't used table of contents before but adding \tableofcontents is producing some garbage data. 

IMHO Blockchain section is at the right place as the report is trying to shed more light first on how in current world economics itself only cryptocurrencies are not something which are solved by blockchain but there are a lot of other problems that are solved with Blockchain/hyperledger technologies. So the order remains as follows:

- Delve deep into world economy and transaction management issues in supply chain
- Major challenges in it which are not even related to any currency or cryptocurrency.
- Blockchain and how its application is proving to be promising in other areas than cryptocurrency.
.. and so on.

Eventually entering into Bigdata in Blockchains.

Please advise if my approach needs to change from this perspective

**Comment by laszewsk** [comment]
unfortunately this theme does not support tableofcontents, so one needs to do it by hand :(

**Comment by lokeshdubey** [comment]
Provided the tableofcontents is not supported I used manual enumeration and itemization to create a sort of outline. As most the things like justified pagenumbers for each of them, hyperlinking within the documents will not work.

Please let me know if the placement is wrong. Because I tried placing this after \maketitle but then it requires a lot of adjustments on spacing and eventually it wants me to use different packages. At this point in time in our proceedings I'm hoping you'd agree it's not good to modify anything on new packages.
